version: '3.8'
services:
  dev-db:
    image: postgres:13
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - CUBlackMarket

  redis-socket:
    image: redis:latest
    container_name: redis
    command: ['redis-server', '--bind', 'redis', '--port', '6379']
    ports:
      - 6379:6379
    networks:
      - CUBlackMarket

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: CUBlackMarket-docker
#     environment:
#       - PORT=${PORT}
#     ports:
#       - 4000:4000
#     depends_on:
#       - dev-db
#     volumes:
#       - ./src:/app/src

networks:
  CUBlackMarket:
